import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "@/lib/storage";

const COLORS = {
  Pass: [22, 163, 74] as [number, number, number],
  Partial: [217, 119, 6] as [number, number, number],
  Fail: [220, 38, 38] as [number, number, number],
  text: [17, 17, 17] as [number, number, number],
  sub: [102, 102, 102] as [number, number, number],
  light: [170, 170, 170] as [number, number, number],
  bg: [245, 245, 245] as [number, number, number],
};

function verdictColor(v: string): [number, number, number] {
  return COLORS[v as keyof typeof COLORS] ?? COLORS.text;
}

function addFooter(doc: jsPDF, page: number) {
  const h = doc.internal.pageSize.height;
  const w = doc.internal.pageSize.width;
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.light);
  doc.text("Generated by Simulo", 20, h - 10);
  doc.text(`${page}`, w - 20, h - 10, { align: "right" });
}

export function generatePDF(data: AnalysisResult): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.width;
  let y = 0;
  let page = 1;

  // ─── Page 1: Cover ───
  y = 80;
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.text);
  doc.text("Simulo", w / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.sub);
  doc.text("UX Analysis Report", w / 2, y, { align: "center" });

  y += 25;
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);
  const hypothesisLines = doc.splitTextToSize(data.hypothesis, w - 60);
  doc.text(hypothesisLines, w / 2, y, { align: "center" });

  y += hypothesisLines.length * 6 + 15;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.sub);
  doc.text(new Date(data.createdAt).toLocaleString(), w / 2, y, { align: "center" });

  y += 6;
  doc.text(`Target: ${data.targetUser}`, w / 2, y, { align: "center" });

  if (data.projectTag) {
    y += 6;
    doc.text(`Project: ${data.projectTag}`, w / 2, y, { align: "center" });
  }

  y += 6;
  doc.text(`Input: ${data.inputType.toUpperCase()}`, w / 2, y, { align: "center" });

  addFooter(doc, page);

  // ─── Page 2: Overview ───
  doc.addPage();
  page++;
  y = 20;

  doc.setFontSize(16);
  doc.setTextColor(...COLORS.text);
  doc.text("Overview", 20, y);

  // Verdict + Score
  y += 12;
  doc.setFontSize(36);
  doc.setTextColor(...COLORS.text);
  doc.text(`${data.score}`, 20, y);

  doc.setFontSize(12);
  doc.setTextColor(...verdictColor(data.verdict));
  doc.text(`${data.verdict}`, 50, y);

  if (data.taskSuccessLikelihood) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.sub);
    doc.text(`Task Success: ${data.taskSuccessLikelihood}`, w - 20, y, { align: "right" });
  }

  // Summary
  y += 12;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.text);
  const summaryLines = doc.splitTextToSize(data.summary, w - 40);
  doc.text(summaryLines, 20, y);
  y += summaryLines.length * 4.5 + 5;

  // Score Breakdown
  if (data.scoreBreakdown) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.text("Score Breakdown", 20, y);
    y += 6;

    const sb = data.scoreBreakdown;
    autoTable(doc, {
      startY: y,
      head: [["Category", "Score", "/25", "Reason"]],
      body: [
        ["Clarity", `${sb.clarity.score}`, "/25", sb.clarity.reason],
        ["Flow", `${sb.flow.score}`, "/25", sb.flow.reason],
        ["Feedback", `${sb.feedback.score}`, "/25", sb.feedback.reason],
        ["Efficiency", `${sb.efficiency.score}`, "/25", sb.efficiency.reason],
      ],
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
      margin: { left: 20, right: 20 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // Desire Alignment
  if (data.desireAlignment) {
    if (y > 240) { doc.addPage(); page++; y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.text("Desire Alignment", 20, y);
    y += 6;

    const da = data.desireAlignment;
    autoTable(doc, {
      startY: y,
      head: [["Desire", "Score", "/10", "Comment"]],
      body: [
        ["Utility", `${da.utility.score}`, "/10", da.utility.comment],
        ["Health & Pride", `${da.healthPride.score}`, "/10", da.healthPride.comment],
        ["Loss Aversion", `${da.lossAversion.score}`, "/10", da.lossAversion.comment],
      ],
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
      margin: { left: 20, right: 20 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // Retention Risk
  if (data.retentionRisk) {
    if (y > 250) { doc.addPage(); page++; y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.text("Retention Risk", 20, y);
    y += 6;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.sub);
    doc.text(`D1: ${data.retentionRisk.d1Risk}  /  D7: ${data.retentionRisk.d7Risk}`, 20, y);
    y += 5;
    const riskLines = doc.splitTextToSize(data.retentionRisk.mainRiskReason, w - 40);
    doc.text(riskLines, 20, y);
    y += riskLines.length * 4.5 + 5;
  }

  // Strengths
  if (data.strengths?.length) {
    if (y > 250) { doc.addPage(); page++; y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.text("Strengths", 20, y);
    y += 6;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.sub);
    for (const s of data.strengths) {
      if (y > 275) { doc.addPage(); page++; y = 20; }
      const lines = doc.splitTextToSize(`+ ${s}`, w - 45);
      doc.text(lines, 25, y);
      y += lines.length * 4.5 + 2;
    }
    y += 3;
  }

  // Top Priorities
  if (data.topPriorities?.length) {
    if (y > 250) { doc.addPage(); page++; y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.text("Top Priorities", 20, y);
    y += 6;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.sub);
    data.topPriorities.forEach((p, i) => {
      if (y > 275) { doc.addPage(); page++; y = 20; }
      const lines = doc.splitTextToSize(`${i + 1}. ${p}`, w - 45);
      doc.text(lines, 25, y);
      y += lines.length * 4.5 + 2;
    });
  }

  addFooter(doc, page);

  // ─── Page 3: Think Aloud ───
  if (data.thinkAloud?.length) {
    doc.addPage();
    page++;
    y = 20;

    doc.setFontSize(16);
    doc.setTextColor(...COLORS.text);
    doc.text("Think Aloud", 20, y);
    y += 12;

    for (const ta of data.thinkAloud) {
      if (y > 265) { doc.addPage(); page++; y = 20; }

      doc.setFontSize(9);
      doc.setTextColor(...COLORS.text);
      doc.text(ta.screen, 20, y);
      y += 5;

      doc.setFontSize(9);
      doc.setTextColor(...COLORS.sub);
      const lines = doc.splitTextToSize(`"${ta.thought}"`, w - 50);
      doc.text(lines, 25, y);
      y += lines.length * 4.5 + 6;
    }

    addFooter(doc, page);
  }

  // ─── Page 4: Issues ───
  if (data.issues?.length) {
    doc.addPage();
    page++;
    y = 20;

    doc.setFontSize(16);
    doc.setTextColor(...COLORS.text);
    doc.text(`Issues (${data.issues.length})`, 20, y);
    y += 8;

    const sorted = [...data.issues].sort((a, b) => {
      const order = { Critical: 0, Medium: 1, Low: 2 };
      return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
    });

    autoTable(doc, {
      startY: y,
      head: [["Severity", "Screen", "Type", "Issue", "Recommendation"]],
      body: sorted.map((issue) => [
        issue.severity,
        issue.screen,
        issue.desireType ?? "-",
        issue.issue,
        issue.recommendation,
      ]),
      theme: "grid",
      styles: { fontSize: 7, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
      columnStyles: {
        0: { cellWidth: 18 },
        1: { cellWidth: 25 },
        2: { cellWidth: 20 },
        3: { cellWidth: 55 },
        4: { cellWidth: 55 },
      },
      margin: { left: 15, right: 15 },
      didParseCell: (hookData) => {
        if (hookData.section === "body" && hookData.column.index === 0) {
          const val = hookData.cell.raw as string;
          if (val === "Critical") hookData.cell.styles.textColor = COLORS.Fail;
          if (val === "Medium") hookData.cell.styles.textColor = COLORS.Partial;
        }
      },
    });

    addFooter(doc, page);
  }

  // Add remaining footers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  return doc;
}
